[project]
name = "bdf_dairy"
version = "0.0.1"
description = "BDF"
authors = [
  { name = "BDF", email = "info@bastardairyfarm.com" }
]
requires-python = ">=3.10"
readme = "README.md"
dependencies = [
  "pandas==2.2.3",
  "openpyxl==3.1.5"
]

[tool.frappe]
app_name = "bdf_dairy"

[tool.bench.frappe-dependencies]
frappe = ">=16.0.0,<17.0.0"
